name: j3enterprise
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.17.3+1
  http: ^0.12.0+4
  find_dropdown: ^0.2.0
  xlive_switch: ^1.0.5
  chopper: ^3.0.0
  easy_localization:
  background_fetch: ^0.6.0
  cupertino_icons: ^0.1.2
  devicelocale: ^0.2.3
  rflutter_alert: ^1.0.3  
  sqflite: ^1.3.0
  shared_preferences: ^0.5.8
  flutter_bloc: ^3.2.0
  meta: ^1.1.6
  equatable: ^1.0.0
  moor: ^3.3.0
  moor_ffi: ^0.8.0
  path_provider: ^1.6.11
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_messaging: ^6.0.16
  bot_toast: ^3.0.0
  device_info: ^0.4.2+4
  encrypt: ^4.0.2
  cryptor: ^0.1.6
  google_fonts: ^1.1.0
  connectivity: ^0.4.8+6
  quiver: ^2.1.3
  logging: ^0.11.4
  kiwi: ^0.1.0
  built_value: ^6.3.0
  flutter_local_notifications: ^1.4.4+1
  get_it: ^4.0.2
  built_collection: ^4.1.0
  overlay_support: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^3.0.0
  moor_generator: ^3.1.0
  build_runner: ^1.3.1
  intl_translation: ^0.17.1


 
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:  
    - images/
    - images/cogs.png
    - lang/en.json
    - lang/es.json
    - lang/sk.json
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: CustomIcons
     fonts:
       - asset: fonts/CustomIcons.ttf
   - family: MyFont
     fonts:
       - asset: fonts/Roboto-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
