name: j3enterprise
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.17.3+1
  google_maps_flutter:
  http: ^0.12.0+4
  geolocator: ^6.1.13
  vector_math: any
  sensors: ^0.4.2+6
  battery: ^1.0.7





#  Screen widgets packages

  material_floating_search_bar: ^0.2.0
  dropdown_search: ^0.4.8
  cupertino_icons: ^0.1.2
  xlive_switch: ^1.0.5
  flushbar: ^1.10.4
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.0
  chopper: ^3.0.0
  flutter_simple_treeview: ^2.0.1
  barcode_keyboard_listener: ^0.0.1
  intl: 
 
  easy_localization:
  background_fetch: ^0.6.0
  devicelocale: ^0.2.3
  rflutter_alert: ^1.0.3  
  sqflite: ^1.3.0
  provider: ^4.3.2+2
  badges: ^1.1.3
  shared_preferences: ^0.5.8
  flutter_bloc: ^3.2.0
  meta: ^1.1.6
  equatable: ^1.0.0
  moor: ^3.3.0
  moor_ffi: ^0.8.0
  path_provider: ^1.6.11
  # firebase_core: ^0.4.0+9
  # firebase_analytics: ^5.0.2
  # firebase_auth: ^0.14.0+5
  firebase_messaging: ^7.0.3
  bot_toast: ^3.0.0
  device_info: ^0.4.2+4
  encrypt: ^4.0.2
  cryptor: ^0.1.6

  connectivity: ^0.4.8+6
  quiver: ^2.1.3
  logging: ^0.11.4
  flutter_barcode_scanner: ^1.0.1
   
  kiwi: ^0.1.0
  built_value: ^7.0.0
  flutter_local_notifications: ^1.4.4+1
  get_it: ^4.0.2
  built_collection: ^4.1.0
  overlay_support: ^1.0.4
  shamsi_date: ^0.8.1
  random_string_one: ^1.0.2
  twilio_flutter: ^0.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^3.0.0
  moor_generator: ^3.1.0
  build_runner: ^1.3.1
   


 
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:  
    - images/
    - images/cogs.png
    - lang/en.json
    - lang/es.json
    - lang/sk.json
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: CustomIcons
     fonts:
       - asset: fonts/CustomIcons.ttf
   - family: MyFont
     fonts:
       - asset: fonts/Roboto-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
