name: j3enterprise
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.1
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  geolocator: ^8.0.3
  vector_math: ^2.1.1
  sensors: ^2.0.3
  battery: ^2.0.3
  material_floating_search_bar: ^0.3.6
  dropdown_search: ^2.0.1
  cupertino_icons: ^1.0.4
  #xlive_switch: ^1.0.5
  flutter_switch: ^0.3.2
  #flushbar: ^1.10.4
  another_flushbar: ^1.10.28
  signature: ^5.0.0
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.2.0
  chopper: ^4.0.4
  flutter_simple_treeview: ^3.0.0-nullsafety.1
  #barcode_keyboard_listener: ^0.0.1
  flutter_barcode_listener: ^0.1.1
  intl: ^0.17.0
  easy_localization: ^3.0.0
  background_fetch: ^1.0.3
  devicelocale: ^0.5.0
  rflutter_alert: ^2.0.4
  sqflite: ^2.0.2
  provider: ^6.0.2
  badges: ^2.0.2
  shared_preferences: ^2.0.12
  flutter_bloc: ^7.2.0
  meta: ^1.7.0
  equatable: ^2.0.3
  drift: ^1.0.0
  #moor_ffi: ^0.8.0
  sqlite3_flutter_libs: ^0.5.3
  path_provider: ^2.0.8
  # firebase_core: ^0.4.0+9
  # firebase_analytics: ^5.0.2
  # firebase_auth: ^0.14.0+5
  firebase_messaging: ^11.2.5
  bot_toast: ^4.0.1
  device_info: ^2.0.3
  encrypt: ^5.0.1
  #cryptor: ^0.1.6
  crypto: ^3.0.1
  random_string_generator: ^2.0.0
  connectivity: ^3.0.6
  quiver: ^3.0.1+1
  logging: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  kiwi: ^4.0.1
  built_value: ^8.1.4
  flutter_local_notifications: ^9.2.0
  get_it: ^7.2.0
  built_collection: ^5.1.1
  shamsi_date: ^1.0.1
  #random_string_one: ^1.0.2
  dotted_line: ^3.1.0
  twilio_flutter: ^0.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^4.0.0
  drift_dev: ^1.0.0
  build_runner: ^2.1.7
# dependency_overrides:
#   analyzer: ^2.3.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/cogs.png
    - lang/en.json
    - lang/es.json
    - lang/sk.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: MyFont
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
